---
region: "us-east-2"

# VPC
vpc_cidr: 10.10.0.0/24
vpc_name: "Staging VPC3"

# Subnet
subnet_name: "Staging Subnet"
subnet_cidr: 10.10.0.0/26

igw_name: "Staging IGW"

#route table name
route_name: "Public Staging Route"

securitygroup_name: "Staging Security Group"

ec2_tag: "WebServer"

#key storage location
ec2_key_directory: "~/.ssh/"
keypair_name: "delta"
